name: demo

type: php:7.1

runtime:
    extensions:
        - apcu
        - mbstring
        - pdo_mysql
        - pdo_pgsql

relationships:
    database: "database2:postgresql"

build:
    flavor: none

web:
    locations:
        "/":
            root: "public"
            expires: 1h
            passthru: "/index.php"

disk: 2048

mounts:
    "/var": "shared:files/var"

hooks:
    build: |
        set -x -e

        curl -s https://get.symfony.com/cloud/configurator | (>&2 bash)
        mv /app/scenv /app/.global/bin/scenv
        (>&2 symfony-build)

    deploy: |
        set -x -e

        (>&2 symfony-deploy)
